on: push
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
      - run: flutter pub get
      - run: flutter build apk --release --no-sound-null-safety
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@v0.3
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          filename: "build/app/outputs/flutter-apk/app-release.apk"
          folderId:  ${{ secrets.FOLDERID }}
          overwrite: "true" # optional boolean
          mimeType: "application/vnd.android.package-archive"
 
 
